import { HomepageItem } from "../../home/HomepageItem";

export const tutorialItems: HomepageItem[] =
[
    {
        title: "Instalar o GTA SA",
        shortDescription: "GTA SA 2.00 + Data + APK + OBB",
        description: "",
        image: "assets/thumbs/tutorials/install-gta.png",
        pageUrl: "https://www.youtube.com/watch?v=AhO4Z6A3wuo",
        videoPreviewId: "AhO4Z6A3wuo",
        openNewPage: true,
        categories: [],
    },
    {
        title: "Colocar LEDs 3D em um carro | ZModeler Android",
        shortDescription: "Place 3D LEDs on a vehicle using ZModeler",
        description: "",
        image: "assets/thumbs/tutorials/leds3d-zmodeler.png",
        pageUrl: "https://www.youtube.com/watch?v=irxNuJfTMek",
        videoPreviewId: "irxNuJfTMek",
        openNewPage: true,
        categories: [],
    },
    {
        title: "Veiculos estacionados na base",
        shortDescription: "Mod PoliceBase",
        description: "",
        image: "assets/thumbs/tutorials/police-base.png",
        pageUrl: "https://www.youtube.com/watch?v=LWPBclW0c_E",
        videoPreviewId: "LWPBclW0c_E",
        openNewPage: true,
        categories: [],
    },
    {
        title: "Criar bases",
        shortDescription: "Mod Policia",
        description: "",
        image: "assets/thumbs/tutorials/mod-policia-bases.png",
        pageUrl: "https://www.youtube.com/watch?v=gihTVyfpTRE",
        videoPreviewId: "gihTVyfpTRE",
        openNewPage: true,
        categories: [],
    },
    {
        title: "Criar remaps / plotagens",
        shortDescription: "Mod MultiRemap",
        description: "",
        image: "assets/thumbs/tutorials/multi-remap-tutorial.png",
        pageUrl: "https://www.youtube.com/watch?v=-eMwAYBImxM",
        videoPreviewId: "-eMwAYBImxM",
        openNewPage: true,
        categories: [],
    },
]